{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77c333eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import xml.etree.ElementTree as ET\n",
    "\n",
    "\n",
    "def get_color_to_channel_dict(microscope='MF3'):\n",
    "    if microscope=='MF3' or \\\n",
    "       microscope=='MF5':\n",
    "        d = dict(zip([np.nan, 405,488,560,650,750],[np.nan,4,3,2,1,0]))\n",
    "    return d\n",
    "\n",
    "def get_frame_table(bead_z , bead_seq, color_seq , end_seq, z_pos, microscope='MF3'):\n",
    "    \"\"\"\n",
    "    For simplicity, the shutter files have the following features:\n",
    "        - fixed number of frames per z position (to have a nZ x m frames)\n",
    "        - first z position is z = 0\n",
    "        - last z position is z = 0\n",
    "        - blank frames have np.nan color\n",
    "    \n",
    "    \"\"\"\n",
    "   \n",
    "    color_2_channel_dict = get_color_to_channel_dict(microscope=microscope)\n",
    "\n",
    "    data = []\n",
    "\n",
    "    # add frames for the imaging of beads at z == bead_z\n",
    "    for i , color in enumerate(bead_seq):\n",
    "        data.append([color, color_2_channel_dict[color], bead_z])\n",
    "\n",
    "    # add frames for the imaging of sample\n",
    "    for z in z_pos:\n",
    "        for c in color_seq:\n",
    "            data.append([c, color_2_channel_dict[c], z])\n",
    "\n",
    "    # add frames for the imaging of beads at z == bead_z\n",
    "    for i , color in enumerate(end_seq):\n",
    "        data.append([color, color_2_channel_dict[color], bead_z])\n",
    "\n",
    "    frame_df = pd.DataFrame(columns=['color', 'channel', 'z'], data=data)\n",
    "            \n",
    "    return frame_df\n",
    "\n",
    "def print_frame_table(df):\n",
    "    \"\"\"\n",
    "    To easily visualize the structure of the shutter file\n",
    "    \"\"\"\n",
    "    \n",
    "    # extract the number of frames per z\n",
    "    counts = df['z'].value_counts()\n",
    "    frames_per_z = min(counts)\n",
    "    \n",
    "    col_width = 6\n",
    "    col_sep = ' '*6\n",
    "    \n",
    "    # Header\n",
    "    header_width = col_width * frames_per_z\n",
    "    print(f'{\"frames\":{header_width}s}{col_sep}'\n",
    "          f'{\"color\":{header_width}s}{col_sep}'\n",
    "          f'{\"channel\":{header_width}s}{col_sep}'\n",
    "          f'{\"z\":{header_width}s}{col_sep}')\n",
    "    print()  # blank line\n",
    "\n",
    "    n = len(df)\n",
    "\n",
    "    for start in range(0, n, frames_per_z):\n",
    "        end = start + frames_per_z\n",
    "        group = df.iloc[start:end]\n",
    "\n",
    "        # Skip incomplete group if desired; remove this if you want to print it\n",
    "        if len(group) < frames_per_z:\n",
    "            break\n",
    "\n",
    "        # Frames (index)\n",
    "        frames_str = ''.join(f'{int(idx):{col_width}d}' for idx in group.index)\n",
    "\n",
    "        # Helper for NaNs in int-like columns\n",
    "        def fmt_int_like(val):\n",
    "            if pd.isna(val):\n",
    "                return f'{\"nan\":>{col_width}}'\n",
    "            return f'{int(val):{col_width}d}'\n",
    "\n",
    "        # Colors\n",
    "        colors_str = ''.join(fmt_int_like(v) for v in group['color'])\n",
    "\n",
    "        # Channels\n",
    "        channels_str = ''.join(fmt_int_like(v) for v in group['channel'])\n",
    "\n",
    "        # z as float with 2 decimals\n",
    "        z_str = ''.join(f'{float(v):{col_width}.2f}' for v in group['z'])\n",
    "\n",
    "        print(f'{frames_str}{col_sep}{colors_str}{col_sep}{channels_str}{col_sep}{z_str}')\n",
    "        \n",
    "def get_color_sequence_name(df):\n",
    "    \"\"\"\n",
    "    Given a DataFrame with a 'color' column, return a succinct name like:\n",
    "    'blkf8_405f2_650f4_750f4'\n",
    "    where:\n",
    "      - 'blk' corresponds to NaN (blank) entries\n",
    "      - other entries are color values (as ints)\n",
    "      - 'fN' is the total count of frames with that color\n",
    "    \"\"\"\n",
    "    col = df['color']\n",
    "\n",
    "    # Count NaNs separately\n",
    "    n_blk = col.isna().sum()\n",
    "\n",
    "    # Count non-NaN colors\n",
    "    counts = col.value_counts(dropna=True)\n",
    "\n",
    "    # Build parts of the name\n",
    "    parts = []\n",
    "\n",
    "    if n_blk > 0:\n",
    "        parts.append(f\"blkf{int(n_blk)}\")\n",
    "\n",
    "    # Sort colors numerically, if they are numeric\n",
    "    # (convert index to float, then int for printing)\n",
    "    for color in sorted(counts.index.astype(float)):\n",
    "        count = int(counts.loc[color])\n",
    "        parts.append(f\"{int(color)}f{count}\")\n",
    "\n",
    "    # Join with underscores\n",
    "    return \"_\".join(parts)\n",
    "\n",
    "def create_shutter_file(df, filename, oversampling=1, default_power=1.0):\n",
    "    \"\"\"\n",
    "    Convert a DataFrame with columns: ['color', 'channel', 'z']\n",
    "    index = frame number (on-time)\n",
    "    to an XML file of events, pretty-printed with CRLF line endings.\n",
    "\n",
    "    Additionally:\n",
    "      - Embed the full frame table (as CSV) into the first XML comment so\n",
    "        that the original z (and full frame info) can be reconstructed\n",
    "        later from the shutter file alone.\n",
    "    \"\"\"\n",
    "    # Ensure index is numeric and sorted\n",
    "    df = df.sort_index()\n",
    "\n",
    "    # Root element\n",
    "    root = ET.Element(\"repeat\")\n",
    "\n",
    "#     # --- Add frame table as CSV in a comment at the beginning ---\n",
    "#     # We include the index as \"frame\"\n",
    "#     csv_buf = io.StringIO()\n",
    "#     df.to_csv(csv_buf, index=True)   # index name will become first column header\n",
    "#     csv_text = csv_buf.getvalue()\n",
    "\n",
    "#     frame_table_comment_text = (\n",
    "#         \"FRAME_TABLE_CSV_START\\n\"\n",
    "#         + csv_text +\n",
    "#         \"FRAME_TABLE_CSV_END\"\n",
    "#     )\n",
    "\n",
    "#     comment_el = ET.Comment(frame_table_comment_text)\n",
    "#     root.append(comment_el)\n",
    "#     # Two empty lines after the comment, before <oversampling>...\n",
    "#     # (minidom/toprettyxml will preserve this as blank lines)\n",
    "#     comment_el.tail = \"\\n\\n\"\n",
    "\n",
    "    # <oversampling>\n",
    "    overs_el = ET.SubElement(root, \"oversampling\")\n",
    "    overs_el.text = str(oversampling)\n",
    "\n",
    "    # <frames>\n",
    "    frames_el = ET.SubElement(root, \"frames\")\n",
    "    frames_el.text = str(len(df))\n",
    "\n",
    "    last_z = None  # to track when z changes and add a comment\n",
    "\n",
    "    for frame, row in df.iterrows():\n",
    "        channel = row[\"channel\"]\n",
    "        z = row[\"z\"]\n",
    "        color = row.get(\"color\", np.nan)  # in case 'color' column might be missing\n",
    "\n",
    "        # Skip non-event frames (NaN channel)\n",
    "        if pd.isna(channel):\n",
    "            continue\n",
    "\n",
    "        # Add comment when z changes (or for the first event)\n",
    "        if (last_z is None) or (z != last_z):\n",
    "            if z == 0 and not pd.isna(color) and int(color) == 405:\n",
    "                comment_text = f\" z = {int(z)} um, 405 beads\"\n",
    "            else:\n",
    "                if float(z).is_integer():\n",
    "                    comment_text = f\" z = {int(z)} um\"\n",
    "                else:\n",
    "                    comment_text = f\" z = {z} um\"\n",
    "            root.append(ET.Comment(comment_text))\n",
    "            last_z = z\n",
    "\n",
    "        # <event>\n",
    "        event_el = ET.SubElement(root, \"event\")\n",
    "\n",
    "        ch_el = ET.SubElement(event_el, \"channel\")\n",
    "        ch_el.text = str(int(channel))\n",
    "\n",
    "        pw_el = ET.SubElement(event_el, \"power\")\n",
    "        pw_el.text = f\"{default_power:.1f}\"\n",
    "\n",
    "        on_el = ET.SubElement(event_el, \"on\")\n",
    "        on_el.text = f\"{float(frame):.1f}\"\n",
    "\n",
    "        off_el = ET.SubElement(event_el, \"off\")\n",
    "        off_el.text = f\"{float(frame + 1):.1f}\"\n",
    "\n",
    "    # ---- Pretty-print + CRLF writing ----\n",
    "    rough_bytes = ET.tostring(root, encoding=\"utf-8\")\n",
    "    dom = minidom.parseString(rough_bytes)\n",
    "    pretty_xml = dom.toprettyxml(indent=\"  \", encoding=\"ISO-8859-1\")  # bytes\n",
    "\n",
    "    # Decode to text (LF newlines for now)\n",
    "    pretty_text = pretty_xml.decode(\"ISO-8859-1\")\n",
    "\n",
    "    # Add an empty line before every comment line for legibility\n",
    "    pretty_text = pretty_text.replace(\"\\n  <!--\", \"\\n\\n  <!--\")\n",
    "\n",
    "    # Normalize to CRLF for Windows\n",
    "    pretty_text = pretty_text.replace(\"\\n\", \"\\r\\n\")\n",
    "\n",
    "    with open(filename, \"w\", encoding=\"ISO-8859-1\", newline=\"\") as f:\n",
    "        f.write(pretty_text)\n",
    "        \n",
    "def format_z_offsets_from_frame_table(df: pd.DataFrame) -> str:\n",
    "    \"\"\"\n",
    "    Build the text for <z_offsets> from the 'z' column of frame_table.\n",
    "\n",
    "    Logic (matches your example):\n",
    "      - Determine group size as the length of a contiguous run of identical z\n",
    "        (assumes all runs have same length).\n",
    "      - Take one z per run (i.e. 0.0, 1.0, 1.5, 2.0, 2.5, 0.0 in your example).\n",
    "      - For each such z, repeat it group_size times.\n",
    "      - Arrange values in rows of 'group_size' values.\n",
    "      - Add a comma after every value except the very last overall value.\n",
    "    \"\"\"\n",
    "    z = df['z'].astype(float).to_list()\n",
    "\n",
    "    # Compute run lengths to infer group size\n",
    "    run_lengths = []\n",
    "    last = None\n",
    "    count = 0\n",
    "    for val in z:\n",
    "        if last is None or val == last:\n",
    "            count += 1\n",
    "        else:\n",
    "            run_lengths.append(count)\n",
    "            count = 1\n",
    "        last = val\n",
    "    if count:\n",
    "        run_lengths.append(count)\n",
    "\n",
    "    group_size = run_lengths[0]\n",
    "    # (Optional sanity check)\n",
    "    if not all(rl == group_size for rl in run_lengths):\n",
    "        raise ValueError(f\"Inconsistent run lengths in z column: {run_lengths}\")\n",
    "\n",
    "    # Unique z per run (in order)\n",
    "    unique_z_per_run = []\n",
    "    last = object()\n",
    "    for val in z:\n",
    "        if val != last:\n",
    "            unique_z_per_run.append(val)\n",
    "            last = val\n",
    "\n",
    "    # Build flat list: each run's z repeated group_size times\n",
    "    values = []\n",
    "    for val in unique_z_per_run:\n",
    "        values.extend([val] * group_size)\n",
    "\n",
    "    # Now format as text for the XML, with commas as specified\n",
    "    lines = []\n",
    "    total = len(values)\n",
    "\n",
    "    for i, val in enumerate(values):\n",
    "        is_last = (i == total - 1)\n",
    "        suffix = '' if is_last else ','  # no comma after very last value\n",
    "        token = f\"{val:.1f}{suffix}\"\n",
    "\n",
    "        row_idx = i // group_size\n",
    "        if len(lines) <= row_idx:\n",
    "            lines.append([])\n",
    "        lines[row_idx].append(token)\n",
    "\n",
    "    # Indentation is mainly cosmetic; important part is comma placement\n",
    "    # We’ll match your style roughly:\n",
    "    #   0.0,  0.0,  0.0,\n",
    "    # etc., with two spaces between tokens.\n",
    "    indent = \"         \"  # 9 spaces, as in your example\n",
    "    inner_lines = []\n",
    "    for row in lines:\n",
    "        inner_lines.append(indent + \"  \".join(row))\n",
    "\n",
    "    # Surround with newlines so ElementTree pretty-prints reasonably.\n",
    "    text = \"\\n\" + \"\\n\".join(inner_lines) + \"\\n      \"\n",
    "    return text\n",
    "\n",
    "def create_hal_config(prefix: str,\n",
    "                      frame_table: pd.DataFrame,\n",
    "                      default_power: Optional[List[float]] = None,\n",
    "                      xml_dir: str or Path = \".\",\n",
    "                      output_dir: str or Path = \".\") -> Path:\n",
    "    \"\"\"\n",
    "    Read '{prefix}.xml' as plain text from xml_dir, update:\n",
    "      - <frames>            -> len(frame_table)\n",
    "      - <default_power>     -> comma-joined default_power (if provided)\n",
    "      - <shutters>          -> '{color_sequence_name}_shutter.xml'\n",
    "      - <z_offsets>         -> formatted from frame_table['z']\n",
    "\n",
    "    Then write '{output_dir}/{prefix}-{color_sequence_name}.xml',\n",
    "    preserving original comments and overall layout as much as possible,\n",
    "    and adding exactly one empty line before each comment for legibility.\n",
    "    \"\"\"\n",
    "    xml_dir = Path(xml_dir)\n",
    "    output_dir = Path(output_dir)\n",
    "\n",
    "    in_path = xml_dir / f\"{prefix}.xml\"\n",
    "    with open(in_path, \"rb\") as f:\n",
    "        raw = f.read()\n",
    "\n",
    "    # Decode and normalize to '\\n' internally\n",
    "    text = raw.decode(\"ISO-8859-1\").replace(\"\\r\\n\", \"\\n\")\n",
    "\n",
    "    # --- 1. frames ---\n",
    "    def repl_frames(m):\n",
    "        open_tag, _, close_tag = m.groups()\n",
    "        return f\"{open_tag}{len(frame_table)}{close_tag}\"\n",
    "\n",
    "    text = re.sub(\n",
    "        r\"(<frames[^>]*>)(.*?)(</frames>)\",\n",
    "        repl_frames,\n",
    "        text,\n",
    "        flags=re.DOTALL,\n",
    "    )\n",
    "\n",
    "    # --- 2. default_power (optional) ---\n",
    "    if default_power is not None:\n",
    "        dp_str = \",\".join(str(v) for v in default_power)\n",
    "\n",
    "        def repl_default_power(m):\n",
    "            open_tag, _, close_tag = m.groups()\n",
    "            return f\"{open_tag}{dp_str}{close_tag}\"\n",
    "\n",
    "        text = re.sub(\n",
    "            r\"(<default_power[^>]*>)(.*?)(</default_power>)\",\n",
    "            repl_default_power,\n",
    "            text,\n",
    "            flags=re.DOTALL,\n",
    "        )\n",
    "\n",
    "    # --- 3. shutters ---\n",
    "    seq_name = get_color_sequence_name(frame_table)\n",
    "    shutters_value = f\"{seq_name}_shutter.xml\"\n",
    "\n",
    "    def repl_shutters(m):\n",
    "        open_tag, _, close_tag = m.groups()\n",
    "        return f\"{open_tag}{shutters_value}{close_tag}\"\n",
    "\n",
    "    text = re.sub(\n",
    "        r\"(<shutters[^>]*>)(.*?)(</shutters>)\",\n",
    "        repl_shutters,\n",
    "        text,\n",
    "        flags=re.DOTALL,\n",
    "    )\n",
    "\n",
    "    # --- 4. z_offsets from frame_table['z'] ---\n",
    "    new_z_block = format_z_offsets_from_frame_table(frame_table)\n",
    "    # new_z_block should already contain leading/trailing newlines and indentation\n",
    "\n",
    "    def repl_z_offsets(m):\n",
    "        open_tag, _, close_tag = m.groups()\n",
    "        return f\"{open_tag}{new_z_block}{close_tag}\"\n",
    "\n",
    "    text = re.sub(\n",
    "        r\"(<z_offsets[^>]*>)(.*?)(</z_offsets>)\",\n",
    "        repl_z_offsets,\n",
    "        text,\n",
    "        flags=re.DOTALL,\n",
    "    )\n",
    "\n",
    "    # --- 5. Ensure exactly one empty line before each comment ---\n",
    "    # Only add an extra blank line if there isn't already one just before the comment.\n",
    "    # Preserve indentation before <!-- by capturing spaces/tabs only.\n",
    "    text = re.sub(\n",
    "        r\"(?<!\\n\\n)\\n([ \\t]*)<!--\",   # a newline, optional spaces/tabs, then <!--\n",
    "        r\"\\n\\n\\1<!--\",\n",
    "        text,\n",
    "    )\n",
    "\n",
    "    # --- 6. Write out with CRLF line endings ---\n",
    "    out_path = output_dir / f\"{prefix}-{seq_name}.xml\"\n",
    "    with open(out_path, \"w\", encoding=\"ISO-8859-1\", newline=\"\") as f:\n",
    "        f.write(text.replace(\"\\n\", \"\\r\\n\"))\n",
    "\n",
    "    return out_path\n",
    "\n",
    "def _strip_whitespace_etree(elem):\n",
    "    \"\"\"\n",
    "    Remove whitespace-only .text and .tail from an ElementTree tree.\n",
    "    This prevents minidom.toprettyxml from inserting extra blank lines.\n",
    "    \"\"\"\n",
    "    # Clean children first\n",
    "    for child in list(elem):\n",
    "        _strip_whitespace_etree(child)\n",
    "        if child.tail is not None and not child.tail.strip():\n",
    "            child.tail = None\n",
    "\n",
    "    # Clean this element's text\n",
    "    if elem.text is not None and not elem.text.strip():\n",
    "        elem.text = None\n",
    "        \n",
    "    \n",
    "def print_xml_raw(path, encoding=\"ISO-8859-1\"):\n",
    "    \"\"\"\n",
    "    Print the XML file exactly as it is on disk.\n",
    "    - Comments are preserved.\n",
    "    - Existing indentation and spacing are preserved.\n",
    "    - CRLF line endings are preserved (or optionally normalized).\n",
    "    \"\"\"\n",
    "    with open(path, \"rb\") as f:\n",
    "        data = f.read()\n",
    "\n",
    "    # Option A: preserve original CRLF exactly\n",
    "    text = data.decode(encoding)\n",
    "    print(text, end=\"\")  # no extra newline at end\n",
    "\n",
    "    # If you prefer normalized LF for your console instead, use:\n",
    "    # text = data.decode(encoding).replace(\"\\r\\n\", \"\\n\")\n",
    "    # print(text, end=\"\")\n",
    "    \n",
    "def get_channel_to_color_dict(microscope='MF3'):\n",
    "    \"\"\"\n",
    "    Invert get_color_to_channel_dict: channel -> color.\n",
    "    \"\"\"\n",
    "    color_to_channel = get_color_to_channel_dict(microscope=microscope)\n",
    "    ch2col = {}\n",
    "    for col, ch in color_to_channel.items():\n",
    "        if pd.isna(ch):\n",
    "            continue\n",
    "        ch2col[int(ch)] = col\n",
    "    return ch2col\n",
    "\n",
    "def read_shutter_file_to_frame_table(filename, microscope='MF3'):\n",
    "    \"\"\"\n",
    "    Recreate a frame table from a shutter XML file created by `create_shutter_file`.\n",
    "\n",
    "    Logic:\n",
    "      - The first XML comment contains the full frame table as CSV, between\n",
    "        the markers 'FRAME_TABLE_CSV_START' and 'FRAME_TABLE_CSV_END'.\n",
    "      - We parse that CSV to recover z for every frame (and can also see\n",
    "        color/channel, if desired).\n",
    "      - We then parse <event> elements to rebuild the actual color/channel\n",
    "        activity per frame (overwriting any color/channel from the CSV\n",
    "        with what the events say).\n",
    "      - Result:\n",
    "          * z comes from the first comment's CSV.\n",
    "          * color & channel come from the events (non-event frames get NaN).\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    frame_df : pandas.DataFrame\n",
    "        Columns: ['color', 'channel', 'z'], indexed by frame number.\n",
    "    \"\"\"\n",
    "    # --- 1. Parse XML with comments preserved ---\n",
    "    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))\n",
    "    tree = ET.parse(filename, parser=parser)\n",
    "    root = tree.getroot()   # <repeat>\n",
    "\n",
    "    # --- 2. Read total number of frames (for sanity) ---\n",
    "    frames_el = root.find(\"frames\")\n",
    "    if frames_el is None or frames_el.text is None:\n",
    "        raise ValueError(\"Could not find <frames> element in shutter file.\")\n",
    "    n_frames = int(float(frames_el.text))\n",
    "\n",
    "    # --- 3. Extract frame table CSV from the first comment ---\n",
    "    csv_text = None\n",
    "    for child in root:\n",
    "        if child.tag is Comment and child.text:\n",
    "            txt = child.text\n",
    "            if \"FRAME_TABLE_CSV_START\" in txt and \"FRAME_TABLE_CSV_END\" in txt:\n",
    "                # Extract between the markers\n",
    "                start = txt.index(\"FRAME_TABLE_CSV_START\") + len(\"FRAME_TABLE_CSV_START\")\n",
    "                end = txt.index(\"FRAME_TABLE_CSV_END\")\n",
    "                csv_body = txt[start:end].strip(\"\\n\")\n",
    "                csv_text = csv_body\n",
    "                break\n",
    "\n",
    "    if csv_text is None:\n",
    "        raise ValueError(\"Could not find FRAME_TABLE_CSV comment in shutter file.\")\n",
    "\n",
    "    # Parse CSV into DataFrame\n",
    "    csv_buf = io.StringIO(csv_text)\n",
    "    # The first column should be \"frame\" (index); we force that to be index_col=0\n",
    "    df_csv = pd.read_csv(csv_buf, index_col=0)\n",
    "    df_csv.index.name = \"frame\"\n",
    "\n",
    "    # Sanity check length\n",
    "    if len(df_csv) != n_frames:\n",
    "        # Not fatal, but warn user\n",
    "        print(f\"Warning: frames in CSV ({len(df_csv)}) != <frames> ({n_frames})\")\n",
    "\n",
    "    # We will take z from the CSV, but color/channel from events\n",
    "    z_series = df_csv[\"z\"].astype(float)\n",
    "\n",
    "    # --- 4. Build inverse color<->channel mapping (in case needed) ---\n",
    "    color_to_channel = get_color_to_channel_dict(microscope=microscope)\n",
    "    channel_to_color = {}\n",
    "    for col, ch in color_to_channel.items():\n",
    "        if pd.isna(col) or pd.isna(ch):\n",
    "            continue\n",
    "        channel_to_color[int(ch)] = float(col)\n",
    "\n",
    "    # --- 5. Walk children again, reading <event> elements ---\n",
    "    events = {}\n",
    "\n",
    "    for child in root:\n",
    "        if child.tag != \"event\":\n",
    "            continue\n",
    "\n",
    "        on_el = child.find(\"on\")\n",
    "        ch_el = child.find(\"channel\")\n",
    "        if on_el is None or ch_el is None:\n",
    "            continue\n",
    "\n",
    "        frame = int(float(on_el.text))\n",
    "        channel = int(ch_el.text)\n",
    "\n",
    "        # Color from channel\n",
    "        color = channel_to_color.get(channel, np.nan)\n",
    "\n",
    "        events[frame] = (color, float(channel))\n",
    "\n",
    "    # --- 6. Build full frame table using:\n",
    "    #       - z from comment-CSV\n",
    "    #       - color/channel from events\n",
    "    #       - NaNs where there is no event\n",
    "    data = []\n",
    "    max_frame = max(n_frames, len(z_series))\n",
    "    for f in range(max_frame):\n",
    "        z = z_series.loc[f] if f in z_series.index else np.nan\n",
    "\n",
    "        if f in events:\n",
    "            color, channel = events[f]\n",
    "        else:\n",
    "            color = np.nan\n",
    "            channel = np.nan\n",
    "\n",
    "        data.append([color, channel, z])\n",
    "\n",
    "    frame_df = pd.DataFrame(data, columns=[\"color\", \"channel\", \"z\"])\n",
    "    frame_df.index.name = \"frame\"\n",
    "    return frame_df\n",
    "\n",
    "def visualize_shutter_sequence(frame_df, title=None, savepath=None):\n",
    "    \"\"\"\n",
    "    Visualize a shutter/frame sequence from a frame table DataFrame, vertically.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    frame_df : pandas.DataFrame\n",
    "        Must have columns ['color', 'channel', 'z'] and integer index = frame.\n",
    "        Typically produced by get_frame_table(...) or\n",
    "        read_shutter_file_to_frame_table(...).\n",
    "\n",
    "    title : str, optional\n",
    "        Title for the plot.\n",
    "    \"\"\"\n",
    "    df = frame_df.copy()\n",
    "    df = df.reset_index().rename(columns={'index': 'frame'})\n",
    "\n",
    "    if df.empty:\n",
    "        print(\"Frame table is empty.\")\n",
    "        return\n",
    "\n",
    "    # Map wavelengths to colors for plotting\n",
    "    wavelength_to_color = {\n",
    "        405.0: '#9467bd',   # purple\n",
    "        488.0: '#1f77b4',   # blue\n",
    "        560.0: '#ff7f0e',   # orange\n",
    "        650.0: '#2ca02c',   # green\n",
    "        750.0: '#d62728',   # red\n",
    "    }\n",
    "    default_col = '#7f7f7f'  # for unknown wavelengths\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(5, 8))\n",
    "\n",
    "    # Determine x-levels (channels on x, frames on y)\n",
    "    active_channels = sorted(df['channel'].dropna().unique())\n",
    "    blank_x = -1  # column where we draw blank frames\n",
    "    all_x = [blank_x] + active_channels\n",
    "\n",
    "    # Ensure sorted by frame so separators and annotations line up\n",
    "    df = df.sort_values('frame')\n",
    "\n",
    "    # Plot one horizontal bar per frame\n",
    "    for _, row in df.iterrows():\n",
    "        frame = int(row['frame'])\n",
    "        ch = row['channel']\n",
    "        wav = row['color']\n",
    "\n",
    "        if pd.isna(ch):\n",
    "            # Blank frame -> black box at \"blank\" column\n",
    "            x_center = blank_x\n",
    "            facecolor = 'black'\n",
    "        else:\n",
    "            x_center = int(ch)\n",
    "            facecolor = wavelength_to_color.get(float(wav), default_col)\n",
    "\n",
    "        ax.barh(\n",
    "            y=frame,\n",
    "            width=0.8,             # bar width in x-direction\n",
    "            left=x_center - 0.4,\n",
    "            height=1.0,            # bar height in y-direction\n",
    "            align='center',\n",
    "            color=facecolor,\n",
    "            edgecolor='k',\n",
    "            linewidth=0.2,\n",
    "        )\n",
    "\n",
    "    # Add horizontal separators between different z positions\n",
    "    # Draw line between frame i and i+1 if z changes\n",
    "    df_sorted = df.sort_values('frame')\n",
    "    prev_frame = None\n",
    "    prev_z = None\n",
    "    for _, row in df_sorted.iterrows():\n",
    "        f = int(row['frame'])\n",
    "        z = row['z']\n",
    "        if prev_frame is not None and z != prev_z:\n",
    "            y_sep = (prev_frame + f) / 2.0\n",
    "            ax.axhline(\n",
    "                y=y_sep,\n",
    "                color='0.7',\n",
    "                linestyle='--',\n",
    "                linewidth=0.5,\n",
    "                zorder=0,\n",
    "            )\n",
    "        prev_frame = f\n",
    "        prev_z = z\n",
    "\n",
    "    ax.set_ylabel(\"Frame\")\n",
    "    ax.set_xlabel(\"Channel / blank\")\n",
    "\n",
    "    if title is None:\n",
    "        title = \"Shutter sequence (vertical)\"\n",
    "    ax.set_title(title)\n",
    "\n",
    "    # x-ticks: \"blank\" column plus actual channels\n",
    "    xticks = all_x\n",
    "    xtick_labels = ['blank'] + [str(int(c)) for c in active_channels]\n",
    "    ax.set_xticks(xticks)\n",
    "    ax.set_xticklabels(xtick_labels)\n",
    "\n",
    "    # Annotate first frame of each z to the right of the top-most channel\n",
    "    if active_channels or True:\n",
    "        # choose a right margin a bit beyond the max x position\n",
    "        right_x = (max(all_x) + 1.0) if all_x else 0.5\n",
    "        by_z = df.groupby('z', sort=True)['frame'].min()\n",
    "        for z_val, f0 in by_z.items():\n",
    "            if pd.isna(z_val):\n",
    "                continue\n",
    "            ax.text(\n",
    "                right_x,\n",
    "                f0,\n",
    "                f\"z={z_val:g}\",\n",
    "                fontsize=8,\n",
    "                va='center',\n",
    "                ha='left',\n",
    "            )\n",
    "\n",
    "    # Limits\n",
    "    if all_x:\n",
    "        ax.set_xlim(min(all_x) - 1, max(all_x) + 2)\n",
    "    else:\n",
    "        ax.set_xlim(-1, 1)\n",
    "\n",
    "    ax.set_ylim(df['frame'].min() - 1, df['frame'].max() + 1)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    \n",
    "    # NEW: save figure if requested\n",
    "    if savepath is not None:\n",
    "        fig.savefig(savepath, dpi=300, bbox_inches='tight')\n",
    "    \n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
